repos:
  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.3
    hooks:
      - id: autoflake
        args: [
          --recursive,
          --in-place,
          --remove-unused-variables,
          --remove-all-unused-imports
        ]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: [
          --profile=black,
          --line-length=88
        ]
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: []
